Repository gwcat0506/DBP_Project, pull requests merged in 2023-05, with the labels that each got.

#24 [Fix] 프로젝트 검색 수정
  src/public/main.html
  src/service/projectService.js
Labels: BE, FIX

#25 [Fix] 프로젝트 검색 날짜 필터 수정
  src/controller/projectController.js
  src/service/projectService.js
Labels: BE, FIX

#27 [Feat] 프로젝트 직원 투입 구현
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#29 [Feat] 프로젝트 마감일 최신순 검색 구현
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#31 [Feat] 직원 경력 및 기술 검색
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#33 [Feat] 직원 평균 평가점수 검색 구현
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#37 [Feat] 평가 조회 구현
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#46 [Feat] 사원 검색
  src/controller/employeeController.js
  src/controller/index.js
  src/router/employeeRouter.js
  src/router/index.js
  src/service/employeeService.js
  src/service/index.js
Labels: FEAT, BE

#48 [Feat] 사원 정보 수정
  src/controller/employeeController.js
  src/router/employeeRouter.js
  src/service/employeeService.js
Labels: FEAT, BE

#49 [Feat] 로그인 비밀번호 보이기 구현
  src/public/css/mypage.css
  src/public/login.html
  src/router/mypageRouter.js
Labels: FE, BE

#51 [Fix]main 페이지 버튼 추가
  src/public/main.html
Labels: BE, FIX

#55 [Fix] 직원 검색, 갱신 수정 및 라우팅 경로 변경
  app.js
  src/public/SignUp.html
  src/public/login.html
  src/public/main.html
  src/public/pj_push.html
  src/router/employeeRouter.js
  src/service/employeeService.js
Labels: BE, FIX

#57 [Fix] 사원 검색 응답값 수정
  src/service/employeeService.js
Labels: FEAT, BE

#58 [mod] 불필요한 파일 및 코드 삭제
  src/controller/userController.js
  src/router/index.js
  src/router/userRouter.js
  src/service/userService.js
Labels: MOD

#66 [Feat]프로젝트 추가 - 직무검색 구현
  src/public/pj_push.html
Labels: FEAT, FE

#68 [Feat] 내 정보 조회 구현
  app.js
  package-lock.json
  package.json
  prisma/schema.prisma
  src/controller/authController.js
  src/controller/index.js
  src/controller/userController.js
  src/public/login.html
  src/public/mypage.html
  src/router/index.js
  src/router/userRouter.js
  src/service/index.js
  src/service/userService.js
  yarn.lock
Labels: FEAT, BE

#71 [Feat] 비밀번호 변경 구현
  src/controller/userController.js
  src/router/userRouter.js
  src/service/userService.js
Labels: FEAT, BE

#79 [Feat]프로젝트 인원 추가
  src/public/pj_push.html
  src/public/projectcreate.html
  src/router/projectRouter.js
Labels: FEAT, FE

#90 [Feat] 프로젝트 상세 보기 구현
  src/public/pj_push.html
  src/public/projectcreate.html
  src/public/projectinquiry.html
  src/service/projectService.js
Labels: FEAT, FE

#92 [Feat]프로젝트 별 더보기 구현
  src/controller/projectController.js
  src/public/main.html
  src/public/pj_push.html
  src/public/projectcreate.html
  src/public/projectinquiry.html
Labels: FEAT, FE

#93 [Fix] 프로젝트 조회 default값 설정
  src/public/main.html
Labels: FEAT, FIX

#96 [Feat] 직원 더보기 구현
  src/public/emp_info.html
  src/public/employee.html
  src/public/projectcreate.html
  src/public/projectinquiry.html
Labels: FEAT, FE

#97 [Fix]직원 더보기 구현
  src/public/project_eval.html
  src/public/projectinquiry.html
  src/service/employeeService.js
Labels: FE, FIX

#99 [Fix] 프로젝트 상세 조회 이슈 해결
  src/service/projectService.js
Labels: BE, FIX

#100 [Fix] 프로젝트 상세 조회 이슈 프론트 반영
  src/controller/employeeController.js
  src/public/emp_info.html
  src/public/projectcreate.html
  src/public/projectinquiry.html
Labels: FE, FIX

#102 [Feat]프로젝트 평가 페이지 제목 구현
  src/public/project_eval.html
Labels: FEAT, FE

#104 [Fix] 페이지 버튼 수정
  src/public/employee.html
  src/public/main.html
Labels: FE, FIX

#105 [Feat] 프로젝트 평가 조회 구현
  src/public/project_eval.html
  src/public/projectinquiry.html
Labels: FEAT, FE

#109 [Feat] 마이페이지 비밀번호 변경 구현
  src/controller/userController.js
  src/public/css/mypage.css
  src/public/mypage.html
  src/public/pj_push.html
  src/router/mypageRouter.js
  src/service/employeeService.js
  src/service/userService.js
Labels: FEAT, FE

#116 [Fix] 프로젝트 상세 보기 이슈 해결
  src/controller/projectController.js
  src/public/login.html
  src/public/mypage.html
  src/public/projectcreate.html
  src/public/projectinquiry.html
  src/service/projectService.js
Labels: FE, FIX

#119 [Fix] 평가보기 title에 직무 추가
  src/public/project_eval.html
Labels: FE, FIX

#120 [hotfix] 직원 투입 종료 날짜 추가
  src/service/projectService.js
Labels: HOTFIX

#121 [Feat] 투입 종료 날짜 추가
  src/controller/userController.js
  src/public/projectinquiry.html
  src/public/roadmap.html
  src/service/userService.js
Labels: FEAT, FE

#122 [Fix] 눈 아이콘 누르면 비밀번호 보기
  src/public/mypage.html
Labels: FE, FIX

#123 [Feat] 직원 투입 종료 구현
  src/controller/projectController.js
  src/router/projectRouter.js
  src/service/projectService.js
Labels: FEAT, BE

#125 [Feat] 직원투입종료 구현
  .DS_Store
  src/.DS_Store
  src/public/projectinquiry.html
Labels: FEAT, FE

#127 [Feat] 프로젝트 직원 삭제 기능 구현
  src/public/main.html
  src/public/projectinquiry.html
Labels: FEAT, FE

#132 [Fix] 마이페이지 수정
  src/public/mypage.html
Labels: FE, FIX

#133 [Fix] 종료일자 검색 이슈 해결
  src/service/projectService.js
Labels: BE, FIX

#135 [Feat] 프로젝트 상세 보기 직원 수 구현
  src/public/mypage.html
  src/public/projectinquiry.html
Labels: FEAT, FE

#137 [Fix]프로젝트 직원투입 평점순
  app.js
  src/public/index.html
  src/public/pj_push.html
Labels: FE, FIX
